version: '3.8'

services:
  backend:
    build:
      context: ./docker
      dockerfile: backend.Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=mysql://user:password@mysql:3306/shift_handover
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - mysql

  frontend:
    build:
      context: ./docker
      dockerfile: frontend.Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=shift_handover
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf

volumes:
  mysql_data: